version: "3"
services:
  se:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - LOGGING_CONF_FILE
      - USER_ID
      - PASSWORD
      - SITE_URL
      - TARGET_INFO_URL
