version: "3"
services:
  se:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    logging:
      driver: syslog
      options:
        syslog-facility: user
        tag: se
    environment:
      - USER_ID
      - PASSWORD
      - SITE_URL
      - TARGET_INFO_URL
